version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${WEB_PORT:-8082}:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
      - Redis__ConnectionString=${REDIS_CONNECTION_STRING:-redis:6379}
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING:-Server=sqlserver;Database=TodoDb;User=sa;Password=YourStrong!Password;TrustServerCertificate=True;}
    depends_on:
      - redis
      - sqlserver
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD_FILE: /run/secrets/sqlserver_password
    secrets:
      - sqlserver_password
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
  redis-data:

secrets:
  sqlserver_password:
    file: ./sqlserver_password.txt