name: Build and Push Docker Image

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

env:
    DOTNET_VERSION: '9.0.x'
    DOCKER_IMAGE_NAME: 'rtoora/docker-demo'

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            # 1. Checkout del código
            - name: Checkout code
              uses: actions/checkout@v4

            # 2. Configurar .NET
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: ${{ env.DOTNET_VERSION }}

            # 3. Restaurar dependencias
            - name: Restore dependencies
              run: dotnet restore

            # 4. Construir la aplicación
            - name: Build
              run: dotnet build --configuration Release --no-restore

            # 5. Iniciar sesión en Docker Hub
            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DocKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            # 6. Construir la imagen Docker
            - name: Build Docker image
              run: |
                docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} ./src/DockerDemo03.Web/
                docker tag ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} ${{ env.DOCKER_IMAGE_NAME }}:latest

            # 7. Subir la imagen a Docker Hub
            - name: Push Docker Image
              run: |
                docker push ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
                docker push ${{ env.DOCKER_IMAGE_NAME }}:latest
