name: Build
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:
env:
    DOTNET_VERSION: '9.0.x'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: ${{ env.DOTNET_VERSION }}

            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --configuration Release --no-restore

            - name: Probando tags number
              run: |
                  echo ${{ github.sha }}
                  echo ${{ github.ref_name }}
                  echo ${{ github.run_number }}
                  SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
                  echo $SHORT_SHA
